version: '3'

services: 

  app: 
    platform: linux/x86_64
    build: 
      context: ./node
    container_name: app
    volumes:
      - ./node:/usr/src/app
    tty: true
    networks: 
      - node-fullcycle
    depends_on:
      - db

  db:
    platform: linux/x86_64
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes: 
      - ./mysql:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - node-fullcycle

  nginx:
    build: 
      context: ./nginx
    image: mbrunogregorio/nginx:latest
    container_name: nginx
    networks: 
      - node-fullcycle
    ports: 
      - "8080:80"

networks: 
  node-fullcycle:
    driver: bridge      